Traceback (most recent call last):
  File "/rds/general/user/dla24/home/thesis/CNN/cox_images+tab50.py", line 244, in <module>
    cindex = concordance_index(-slide_risks, slide_times, slide_events)
  File "/rds/general/user/dla24/home/miniforge3/envs/thesis-hpc/lib/python3.10/site-packages/lifelines/utils/concordance.py", line 94, in concordance_index
    return _concordance_ratio(num_correct, num_tied, num_pairs)
  File "/rds/general/user/dla24/home/miniforge3/envs/thesis-hpc/lib/python3.10/site-packages/lifelines/utils/concordance.py", line 99, in _concordance_ratio
    raise ZeroDivisionError("No admissable pairs in the dataset.")
ZeroDivisionError: No admissable pairs in the dataset.
=>> PBS: job killed: walltime 86489 exceeded limit 86400
